### ISSUE TITLE
User defined storage pattern

### ISSUE THREAD

**Issue by muesli4** [gekmihesg/pass-manager#1]
It would be helpful if one could modify the pattern in which passwords are stored. Personally, I store a password in the path: **web**/**<domain>**/**<account>**.

This is especially important, when _firefox_ and _thunderbird_ share passwords.

**Comment by gekmihesg** [comment]
A full user defined storage pattern would be inefficient in most cases, because you would have to decrypt the whole tree for every site you visit to check if there are saved passwords for it.
But with the new option `save_as_username` from 490260dbc19c05822cbd6538f49590050eb69d6b, you can get the same result like this:

``` JS
user_pref("extensions.passmanager.realm", "web");
user_pref("extensions.passmanager.realm.append_product", false);
user_pref("extensions.passmanager.save_as_username", true);
```

Btw, setting `append_product` to `false` already made it possible to share passwords between FF and TB in previous versions.
