### ISSUE TITLE
pass-manager still stores data in Firefox DB

### ISSUE THREAD

**Issue by SnowySailor** [gekmihesg/pass-manager#3]
I'm looking and I still see this extension saving passwords into the default Firefox DB. It looks like that's just in some conditional in the JavaScript file involving a function isFirefoxAccount or something like that. Maybe there could be an option in the about:config to disable this and only use /usr/bin/pass to store the passwords.

This is a useful extension definitely, but it would be nice to not have to store the passwords in the Firefox default DB.

**Comment by gekmihesg** [comment]
isFirefoxAccount just checks, whether the password Firefox wants to store is your [Firefox Account](https://wiki.mozilla.org/Identity/Firefox-Accounts#About_Firefox_Accounts). This account it treated special by Firefox, even without pass-manager (it is stored to signedInUser.json in the profile directory instead of the default password database). pass-manager has to mimic this behaviour, since storing it in pass breaks features like Firefox Sync. If you don't use your Firefox Account, no passwords should be stored anywhere different than pass. I don't see any reason to make it possible to disable this behaviour, because the storing the account data to pass makes storing it useless anyway. Also, the Firefox Account data doesn't seem to contain passwords, just some OAuth and session tokens.
Installing the extension does not delete your default password database, you have to disable the extension, clear your old database and re-enable it.
Do you still see Firefox adding passwords to its internal DB after that?

**Comment by SnowySailor** [comment]
Oh I see what's happening. Since I entered my GPG key password, the extension didn't request it when I went to view my saved passwords in my FF preferences. The extension was saving all the passwords with `pass` after all. Sorry about the misunderstanding.
